### ISSUE TITLE
Ragdoll mover “tried to use a NULL entity!”

### ISSUE THREAD

**Issue by JakeTheOctoling** [Winded/RagdollMover#23]
![image](https://github.com/Winded/RagdollMover/assets/73717904/d9c15242-ea04-4f91-afca-d6bb83db4e4a)
So I have composite bone merge tool and I’m trying to animate the hair using ragdoll mover, but this keeps on happening. I don’t know what is going on here.

**Comment by penolakushari** [comment]
Composite bonemerge issues should be fixed by now
