### ISSUE TITLE
Misaligned Gizmos/Movement Arrows 2: Ragdoll Bone Correction Feature Proposal

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [Winded/RagdollMover#35]
Okay, while I understand it might sound too far fetched, what about implementing a .qc bone orientation editor/correction feature into the Ragdoll Mover, so the gizmos won't look out of place anymore on most ragdolls like the Scout?

**Comment by MrTheshadowon** [comment]
that's not how it works. .qc files are the make up for the model on the source engine, what you're proposing cannot be done.

**Comment by ToxicHolyGrenade** [comment]
> that's not how it works. .qc files are the make up for the model on the source engine, what you're proposing cannot be done.

Then what would you propose? Any ideas?

**Comment by penolakushari** [comment]
Does this warrant creating a 2nd issue?

**Comment by ToxicHolyGrenade** [comment]
> Does this warrant creating a 2nd issue?

What do you mean?

**Comment by penolakushari** [comment]
Creating second issue here, whereas you did initially suggest this idea in the #27. Personally I don't see this as too much of an issue to warrant making gizmo angle adjustment feature, as I think by the time you'd set up that as you want, you might've already posed the ragdoll wherever you've wanted by using positioning gizmo with its 2 axis moving planes.

**Comment by ToxicHolyGrenade** [comment]
The reason why I did that is because I felt like you didn't get the message, so I have to do a follow-up issue that suggests a feature to fix the angle problems that some ragdolls possess. However, I am by no means an expert within the field of computing and coding, which is why I created this issue in hopes that someone would put my solutions on board.

**Comment by ToxicHolyGrenade** [comment]
@penolakushari The reason why I did that is because I felt like you didn't get the message, so I have to do a follow-up issue that suggests a feature to fix the angle problems that some ragdolls possess. However, I am by no means an expert within the field of computing and coding, which is why I created this issue in hopes that someone would put my solutions on board.

**Comment by penolakushari** [comment]
I did get your message the first time
