### ISSUE TITLE
When I click on a body part in the menu, The colored circles values change by themselves

### ISSUE THREAD

**Issue by SonicThomasGamer** [Winded/RagdollMover#59]
seems to only happen on characters clothing, skirts and stuff

**Comment by SonicThomasGamer** [comment]
No the body parts don't move they stay in place,

clothes change by themselves when I click off of them

my mistake, I misremembered

**Comment by penolakushari** [comment]
i don't quite understand what you mean exactly, perhaps you could provide some screenshots or videos of the problem?

**Comment by SonicThomasGamer** [comment]
[https://youtu.be/cnYCSVj8xnQ](url)

**Comment by penolakushari** [comment]
thanks, i think i see it now - that's the general issue on workshop version of the tool so far, it is fixed on the current git branch, though apparently i've neglected to put newer versions as releases. if you'd like you can download the wip version from the master branch here and test it out, i hope to have most of the polishing/testing to the wip version done soon so it would be possible to put on workshop without much issues

**Comment by penolakushari** [comment]
yeah, as you get to the ragdoll mover repo, there will be a green button with "Code" text on it, click on it and it'll open a pop up window, there'll be "download zip" at the bottom, which you'll have to open with some archive program like 7zip and then put the folder from inside of it into gmod's addon folder, that should be the simplest way, though there are also ways to do that through SVNs and other programs, but for those there's a bunch of tutorials on the internet if you'd like to look into those
